cluster_name = "demo"
availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"] 
number_of_nodes = "2"
max_size = "5"
min_size = "1"
node_instance_type = "t2.medium"
vpc_cidr = "10.0.0.0/16"
number_of_subnets = "3"
route_tables = "3"